version: '3.8'
services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: "osrm-routed --algorithm mld /data/new-york.osrm"

  postgres:
    image: postgres:15-alpine
    container_name: greenlink_db
    environment:
      POSTGRES_DB: greenlink
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  backend-python:
    build: ./backend-python
    container_name: greenlink_python
    restart: always
    ports:
      - "8000:8000"

  backend-java:
    build: ./backend-java
    container_name: greenlink_java
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/greenlink
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123
      APP_CORS_ALLOWED_ORIGINS: http://localhost:3000
      APP_OSRM_BASE_URL: http://osrm:5000
      APP_SOLVER_BASE_URL: http://backend-python:8000
      JWT_SECRET: ChangeMeToA32ByteMinimumSecretKey123456
    depends_on:
      - postgres
      - backend-python
      - osrm

  frontend-next:
    build: ./frontend-next
    container_name: greenlink_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    depends_on:
      - backend-java

volumes:
  postgres_data: